import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faUser, 
  faUsers, 
  faBuilding, 
  faGraduationCap,
  faVoteYea,
  faUserCheck,
  faChartBar,
  faLock,
  faUserPlus,
  faHome,
  faCog,
  faSignOutAlt,
  faBell,
  faSearch,
  faEdit,
  faTrash,
  faPlus,
  faTimes,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faSpinner,
  faCalendar,
  faClock,
  faEnvelope,
  faPhone,
  faImage,
  faFileUpload,
  faEye,
  faEyeSlash,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faBars,
  faX,
  faHeart,
  faShieldAlt,
  faBookOpen
} from '@fortawesome/free-solid-svg-icons';
import { 
  faUser as faUserRegular,
  faBell as faBellRegular
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faUser, 
  faUsers, 
  faBuilding, 
  faGraduationCap,
  faVoteYea,
  faUserCheck,
  faChartBar,
  faLock,
  faUserPlus,
  faHome,
  faCog,
  faSignOutAlt,
  faBell,
  faSearch,
  faEdit,
  faTrash,
  faPlus,
  faTimes,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faSpinner,
  faCalendar,
  faClock,
  faEnvelope,
  faPhone,
  faImage,
  faFileUpload,
  faEye,
  faEyeSlash,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faBars,
  faX,
  faHeart,
  faShieldAlt,
  faBookOpen,
  faUserRegular,
  faBellRegular
);

export default library;

